version: '3.8'

services:
  test-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_TAG}
    container_name: octo-billing-test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
