name: Build and Push to Artifactory

# on:
#   push:
#     branches: [ main ]

env:
  ARTIFACTORY_REGISTRY: tbd
  IMAGE_NAME: octo-billing

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to JFrog Artifactory
      uses: docker/login-action@v2
      with:
        registry: ${{ env.ARTIFACTORY_REGISTRY }}
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Generate provenance attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build.outputs.digest }}
