name: integration-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  itests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Enable Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Install dependencies
        run: npm ci || npm i

      - name: Build Docker image for itests
        run: docker build -t octo-billing:itest .

      - name: Run integration tests (JSON)
        run: npm run test:it:json

      - name: Upload integration report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: itest-report
          path: coverage/integration/itest-report.json

      - name: Attest integration test report
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: coverage/integration/itest-report.json
