name: "Setup JFrog CLI OIDC Example"
on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  JF_URL: ${{ vars.JF_URL }}
  JF_REGISTRY: ${{ vars.JF_REGISTRY }}
  JF_DOCKER_REPO: dev-docker-local
  IMAGE_NAME: octo-billing
  BUILD_NAME: octo-billing-build
  OIDC_PROVIDER_NAME: MCodeVisionary/octo-billing@github

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Setup JFrog CLI
        id: setup-jfrog-cli
        uses: jfrog/setup-jfrog-cli@v4.5.13
        with:
          JF_URL: ${{ vars.JF_URL }}
          oidc-provider-name: ${{ env.OIDC_PROVIDER_NAME }}

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          

      - name: Sign in to Artifactory Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.JF_URL }}
          username: ${{ steps.setup-jfrog-cli.outputs.oidc-user }}
          password: ${{ steps.setup-jfrog-cli.outputs.oidc-token }}
