name: Promote Release to Production

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'Image name to promote'
        default: 'octo-billing'
        required: true
        type: string
      image-version:
        description: 'Image version to promote'
        required: true
        type: string

env:
  OIDC_PROVIDER_NAME: swampup-2025/octo-billing@github
  JF_URL: ${{ vars.JF_URL }}
  JF_REGISTRY: ${{ vars.JF_REGISTRY }}
  JF_DOCKER_REPO: dev-docker-local
  JF_PROD_DOCKER_REPO: prod-docker-local

jobs:
  promote-to-production:
    runs-on: self-hosted
    permissions:
        contents: read
        packages: write
        attestations: write  # Required for attestation
        id-token: write      # Added for OIDC token access
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
  
      - name: Install JFrog CLI
        id: setup-jfrog-cli
        uses: jfrog/setup-jfrog-cli@v4.5.13
        env:
          JF_URL: ${{ env.JF_URL }}
        with:
          version: 2.78.5
          oidc-provider-name: ${{ env.OIDC_PROVIDER_NAME }}
          custom-server-id: github-actions

      - name: Verify Provenance and Test Results
        run: |
          echo "## Attestation Verification" >> $GITHUB_STEP_SUMMARY
          echo "Verifying provenance and test results for ${{ github.event.inputs.image-name }}:${{ github.event.inputs.image-version }}..." >> $GITHUB_STEP_SUMMARY
          jf evd verify --package-repo-name ${{ env.JF_DOCKER_REPO }} \
          --package-name ${{ github.event.inputs.image-name }} \
          --package-version ${{ github.event.inputs.image-version }} >> $GITHUB_STEP_SUMMARY
          echo "✅ Provenance and test results verification completed" >> $GITHUB_STEP_SUMMARY

      - name: Promote Docker Image to Production Repository
        run: |
          echo "## Docker Image Promotion" >> $GITHUB_STEP_SUMMARY
          echo "Promoting Docker image to production repository..." >> $GITHUB_STEP_SUMMARY
          jf rt docker-promote  ${{ github.event.inputs.image-name }}/${{ github.event.inputs.image-version }} ${{ env.JF_DOCKER_REPO }} ${{ env.JF_PROD_DOCKER_REPO }} >> $GITHUB_STEP_SUMMARY
        
